import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"], // specify desired font weights
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ComX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} transition-all ease-in-out duration-500 bg-[#F8FAFB] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
